config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    unauthenticated { root to: "devise/sessions#new", as: :unauthenticated_root }

    resource :profile, only: [:edit, :update], controller: :profile
    resource :password, only: [:update, :edit], controller: :password
    resources :generated_images, only: [:index, :show]
    resources :prompts, only: [:new, :create, :show]

    authenticate :user, -> (user) { user.maintainer? } do
      draw :maintenance
    end

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :admin
    end
  end

  root "prompts#new"
end

app/views/sidebar/_content.html.slim
.flex-1.pt-5.pb-4.overflow-y-auto class=(media == :mobile ? "h-0" : "flex flex-col")
  .flex.items-center.flex-shrink-0.px-4 data={ "collapse-target": "logo" }
    = image_tag "logo.svg", class: "h-16 w-auto", alt: "logo"
    - I18n.available_locales.each do |locale|
        - if I18n.locale != locale
          = link_to t("#{locale}"), url_for(locale: locale), class:"hidden md:block text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-2.5 py-1 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 m-2"
  = render "sidebar/menu"
.flex-shrink-0.flex.items-center.justify-between.border-t.border-gray-500.p-4
  = link_to edit_profile_path, class: "flex-shrink-0 group block" do
    .flex.items-center
      div
        - if current_user.avatar_url.present?
          = rounded_image(current_user.avatar_url, 40)
        - else
          = rounded_image(current_user.photo, 40)
      .ml-3 data={ "collapse-target": "other" }
        p.text-sm.font-medium.text-white = current_user.full_name
        p.text-xs.font-medium.text-indigo-200.group-hover:text-white = t(".view_profile")

  = button_to destroy_user_session_path, method: :delete, data: { "collapse-target": "other" } do
    i.fa-solid.fa-arrow-right-from-bracket.text-white

app/views/sidebar/_desktop.html.slim
.hidden.md:flex.md:w-64.md:flex-col.md:fixed.md:inset-y-0 data={ controller: "collapse", "collapse-target": "container", expanded: "1" }
  .flex-1.flex.flex-col.min-h-0.bg-stone-900
    = render "sidebar/content", media: :desktop

app/views/sidebar/_menu.html.slim
nav.mt-10.flex-1.px-2.space-y-1
  = render MenuLinkComponent.new(title: t("menu.maintenance"),
    icon: "fa-house",
    path: maintenance_path,
    policy: MaintenancePolicy.role_can_access?,
    controllers: %w[maintenance/base maintenance maintenance/users])

  = render MenuLinkComponent.new(title: t("menu.admin"),
    icon: "fa-house",
    path: admin_path,
    policy: AdminPolicy.role_can_access?)

  = render MenuLinkComponent.new(title: t("menu.users"),
    icon: "fa-user-group",
    path: admin_users_path,
    policy: AdminPolicy.role_can_access?)

  = render MenuLinkComponent.new(title: t("menu.new_prompt"),
    icon: "fa-folder-open",
    path: new_prompt_path)

  = render MenuLinkComponent.new(title: t("menu.history"),
    icon: "fa-inbox",
    path: generated_images_path)

  absolute.hidden.md:flex.md:justify-end.right-2.top-2.cursor-pointer.p-4 data={ "action": "click->collapse#toggle", "collapse-target": "icon" }
    svg.h-6.w-6.text-white[xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor"]
      path[stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 19l-7-7 7-7m8 14l-7-7 7-7"]

app/views/sidebar/_mobile.html.slim
.relative.z-40.hidden.md:hidden role="dialog" aria-modal="true" data={ "sidebar-target": "container" }
  .fixed.inset-0.bg-stone-600.bg-opacity-75.transition-opacity[
    data={ "sidebar-target": "backdrop" }
    data-transition-enter="ease-in-out duration-500"
    data-transition-enter-start="opacity-0"
    data-transition-enter-end="opacity-100"
    data-transition-leave="ease-in-out duration-500"
    data-transition-leave-start="opacity-100"
    data-transition-leave-end="opacity-0"
  ]
  .fixed.inset-0.flex.z-40
    .relative.flex-1.flex.flex-col.max-w-xs.w-full.bg-stone-900[
      data={ "sidebar-target": "panel" }
      data-transition-enter="transform transition ease-in-out duration-500 sm:duration-700"
      data-transition-enter-start="-translate-x-full"
      data-transition-enter-end="translate-x-0"
      data-transition-leave="transform transition ease-in-out duration-500 sm:duration-700"
      data-transition-leave-start="translate-x-0"
      data-transition-leave-end="-translate-x-full"
    ]
      .absolute.top-0.right-0.-mr-12.pt-2[
        data={ "sidebar-target": "closeButton" }
        data-transition-enter="ease-in-out duration-500"
        data-transition-enter-start="opacity-0"
        data-transition-enter-end="opacity-100"
        data-transition-leave="ease-in-out duration-500"
        data-transition-leave-start="opacity-100"
        data-transition-leave-end="opacity-0"
      ]
        = button_tag type: "button",
          data: { action: "sidebar#hide" },
          class: "ml-1 flex items-center justify-center h-10 w-10 rounded-full focus:outline-none focus:ring-2 focus:ring-inset focus:ring-white" do
          span.sr-only
            | Close sidebar
          svg.h-6.w-6.text-white[xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true"]
            path[stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12"]
      = render "sidebar/content", media: :mobile

    .flex-shrink-0.w-14[aria-hidden="true"]

.flex.sticky.top-0.z-10.md:hidden.pl-1.pt-1.sm:pl-3.sm:pt-3.bg-gray-100
  = button_tag type: "button",
    data: { action: "sidebar#show" },
    class: "-ml-0 5 -mt-0 5 h-12 w-12 inline-flex items-center justify-center rounded-md text-gray-500 hover:text-gray-900 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-indigo-500" do
    span.sr-only
      | Open sidebar
    svg.h-6.w-6 xmlns="http://www.w3.org/2000/svg" fill="none" viewbox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true"
      path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16"
  - I18n.available_locales.each do |locale|
    - if I18n.locale != locale
      = link_to t("#{locale}"), url_for(locale: locale), class:"text-gray-900 bg-white hover:bg-gray-100 border border-gray-200 focus:ring-4 focus:outline-none focus:ring-gray-100 font-medium rounded-lg text-sm px-2.5 py-1 text-center inline-flex items-center dark:focus:ring-gray-600 dark:bg-gray-800 dark:border-gray-700 dark:text-white dark:hover:bg-gray-700 m-2"