config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    unauthenticated { root to: "devise/sessions#new", as: :unauthenticated_root }

    resource :profile, only: [:edit, :update], controller: :profile
    resource :password, only: [:update, :edit], controller: :password
    resources :generated_images, only: [:index, :show]
    resources :prompts, only: [:new, :create, :show]

    authenticate :user, -> (user) { user.maintainer? } do
      draw :maintenance
    end

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :admin
    end
  end

  root "prompts#new"
end

app/controllers/password_controller.rb
# frozen_string_literal: true

class PasswordController < ApplicationController
  before_action :set_user, only: %i[edit update]

  def edit
  end

  def update
    if @user.update_with_password(password_params)
      bypass_sign_in @user
      redirect_to edit_password_path, notice: t(".update_success")
    else
      render :edit, status: :unprocessable_entity, alert: t(".invalid_password")
    end
  end

  private

  def password_params
    params.require(:user).permit(:current_password, :password, :password_confirmation)
  end

  def set_user
    @user = current_user
  end
end

app/views/password/edit.html.slim
= render TabsHeaderComponent.new(title: t(".title"),
  links: [{ title: t(".title"), target: edit_profile_path, data: {turbo_frame: :_top} },
    { title: t(".password"), target: edit_password_path, data: {turbo_frame: :_top} }])

= simple_form_for @user, url: password_path, html: { method: :put, id: :edit_password } do |f|
  = render FormComponent.new do |c|
    = f.input :current_password, autocomplete: "off", placeholder: t("placeholders.current_password"), input_html: { type: "password" }
    = f.input :password, autocomplete: "off", placeholder: t("placeholders.new_password"), input_html: { type: "password" }
    = f.input :password_confirmation, autocomplete: "off", placeholder: t("placeholders.confirm_new_password"), input_html: { type: "password" }
    - c.with_action do
      = f.submit t("update"), class: "btn btn-primary"