config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  devise_scope :user do
    unauthenticated { root to: "devise/sessions#new", as: :unauthenticated_root }

    resource :profile, only: [:edit, :update], controller: :profile
    resource :password, only: [:update, :edit], controller: :password
    resources :generated_images, only: [:index, :show]
    resources :prompts, only: [:new, :create, :show]

    authenticate :user, -> (user) { user.maintainer? } do
      draw :maintenance
    end

    authenticate :user, -> (user) { user.admin? || user.maintainer? } do
      draw :admin
    end
  end

  root "prompts#new"
end

app/models/generated_image.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: generated_images
#
#  id         :bigint           not null, primary key
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  prompt_id  :bigint           not null
#
# Indexes
#
#  index_generated_images_on_prompt_id  (prompt_id)
#
# Foreign Keys
#
#  fk_rails_...  (prompt_id => prompts.id)
#
class GeneratedImage < ApplicationRecord
  belongs_to :prompt
  has_one_attached :image do |a|
    a.variant :thumb, resize_to_fit: [200, 200]
    a.variant :large, resize_to_fit: [1200, 1200]
  end
  delegate :description, to: :prompt
end

app/controllers/generated_images_controller.rb
# frozen_string_literal: true

require "open-uri"

class GeneratedImagesController < ApplicationController
  def index
    @pagy, @generated_images = pagy(Current.user.generated_images.includes(:prompt).order(created_at: :desc), items: 6)

    render "scrollable_list" if params[:page]
  end

  def show
    @generated_image = Current.user.generated_images.includes(:prompt).find(params[:id])
  end
end

app/views/generated_images/_form.html.slim
. data-toggle-target="content"
  = simple_form_for @prompt, url: generated_images_path do |f|
    = render FormComponent.new do |c|
      = f.input :description, placeholder:  t("placeholders.new_prompt"), class: "text-input", label: false

      - c.with_action do
        = f.submit t("generate"), class: "btn btn-primary"

app/views/generated_images/_generated_image.html.slim
= turbo_frame_tag dom_id(generated_image), class:"flex w-1/3 flex-wrap" do
  .w-full.p-1.md:p-2.relative
    = link_to rails_blob_path(generated_image.image, disposition: "attachment", download: "image"), target: "_blank" do
      = image_tag generated_image.image.variant(:large), class: "block h-full w-full rounded-lg object-cover object-center"
      .opacity-0.hover:opacity-100.backdrop-blur-sm.duration-300.absolute.inset-0.z-10.flex.justify-center.items-center.text-white.text-sm.font-medium = generated_image.description

app/views/generated_images/_next_page.html.slim
= turbo_frame_tag "images-page-#{@pagy.next}", loading: :lazy, src: pagy_url_for(@pagy, @pagy.next) do
  .flex.justify-center
  . role="status"
      svg aria-hidden="true" class="w-8 h-8 mr-2 text-gray-200 animate-spin dark:text-gray-600 fill-blue-600" viewBox="0 0 100 101" fill="none" xmlns="http://www.w3.org/2000/svg"
          path d="M100 50.5908C100 78.2051 77.6142 100.591 50 100.591C22.3858 100.591 0 78.2051 0 50.5908C0 22.9766 22.3858 0.59082 50 0.59082C77.6142 0.59082 100 22.9766 100 50.5908ZM9.08144 50.5908C9.08144 73.1895 27.4013 91.5094 50 91.5094C72.5987 91.5094 90.9186 73.1895 90.9186 50.5908C90.9186 27.9921 72.5987 9.67226 50 9.67226C27.4013 9.67226 9.08144 27.9921 9.08144 50.5908Z" fill="currentColor"
          path d="M93.9676 39.0409C96.393 38.4038 97.8624 35.9116 97.0079 33.5539C95.2932 28.8227 92.871 24.3692 89.8167 20.348C85.8452 15.1192 80.8826 10.7238 75.2124 7.41289C69.5422 4.10194 63.2754 1.94025 56.7698 1.05124C51.7666 0.367541 46.6976 0.446843 41.7345 1.27873C39.2613 1.69328 37.813 4.19778 38.4501 6.62326C39.0873 9.04874 41.5694 10.4717 44.0505 10.1071C47.8511 9.54855 51.7191 9.52689 55.5402 10.0491C60.8642 10.7766 65.9928 12.5457 70.6331 15.2552C75.2735 17.9648 79.3347 21.5619 82.5849 25.841C84.9175 28.9121 86.7997 32.2913 88.1811 35.8758C89.083 38.2158 91.5421 39.6781 93.9676 39.0409Z" fill="currentFill"

      span class="sr-only" Loading...

app/views/generated_images/_prompt.html.slim
.flex.justify-center
  = link_to t(".new_prompt"), new_generated_image_path, class: "btn mb-8", data: { turbo_frame: "_top" }
- if @prompt.generated_images.any?
  .grid.grid-cols-1.md:grid-cols-3.gap-4.place-items-start
    - @prompt.generated_images.each do |generated_image|
      = link_to rails_blob_path(generated_image.image, disposition: "attachment", download: "image"), target: "_blank" do
        = image_tag generated_image.image.variant(:thumb), class: "h-auto max-w-full rounded-lg"
- else
  p = t("sorry_nothing")

app/views/generated_images/create.turbo_stream.slim
= turbo_stream.update Prompt.new, ""
= turbo_stream.remove "image_generation_pulse"
= turbo_stream.append "generated_images" do
  = render "prompt", prompt: @prompt

app/views/generated_images/index.html.slim
- content_for :title do
  = t(".collection")

.container.mx-auto.px-5.py-2.lg:px-32.lg:pt-12
  .-m-1.flex.flex-wrap.md-m-2
    = render @generated_images
  = render "generated_images/next_page"

app/views/generated_images/scrollable_list.html.slim
= turbo_frame_tag "images-page-#{@pagy.page}" do
  .-m-1.flex.flex-wrap.md-m-2
    = render @generated_images
    = render "generated_images/next_page"

app/views/generated_images/show.html.slim
= render @generated_image